# Generated by Django 5.2.3 on 2025-06-15 05:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id_conducteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('num_tel', models.CharField(max_length=10, unique=True)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type_vehicule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id_trajet', models.AutoField(primary_key=True, serialize=False)),
                ('point_depart', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('point_arrive', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('heure_depart', models.DateTimeField()),
                ('duree', models.TimeField()),
                ('place_libre', models.IntegerField()),
                ('id_conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Convoiturage.conducteur')),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id_passager', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=100)),
                ('num_tel', models.CharField(max_length=10, unique=True)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Convoiturage.conducteur')),
                ('id_trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Convoiturage.trajet')),
            ],
        ),
        migrations.AddIndex(
            model_name='trajet',
            index=models.Index(fields=['point_depart'], name='Convoiturag_point_d_18bf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='trajet',
            index=models.Index(fields=['point_arrive'], name='Convoiturag_point_a_ee741e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trajet',
            unique_together={('heure_depart', 'id_conducteur')},
        ),
    ]
