# Generated by Django 5.2.3 on 2025-06-17 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='num_tel',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='uniquement 10 chiffres.', regex='^\\d{10}$')]),
        ),
    ]
