# Generated by Django 5.2.3 on 2025-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='duree',
            field=models.DurationField(blank=True, null=True, verbose_name='durée du trajet'),
        ),
    ]
