# Generated by Django 5.2.3 on 2025-06-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='mot_de_passe',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='passager',
            name='mot_de_passe',
            field=models.CharField(max_length=150),
        ),
    ]
