# Generated by Django 5.2.3 on 2025-06-18 01:21

import datetime
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0002_alter_utilisateur_num_tel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trajet',
            options={'ordering': ['date_depart', 'heure_depart', 'duree'], 'verbose_name': 'Trajet', 'verbose_name_plural': 'Trajets'},
        ),
        migrations.RemoveIndex(
            model_name='trajet',
            name='Convoiturag_point_d_18bf5b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trajet',
            name='Convoiturag_point_a_ee741e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='trajet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trajet',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Trajet actif'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='conducteur',
            field=models.ForeignKey(default=1, limit_choices_to={'is_conducteur': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trajets_proposes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trajet',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trajet',
            name='date_depart',
            field=models.DateField(default=datetime.date(2025, 1, 1), verbose_name='Date de départ'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description du trajet'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name="Lieu d'arrivée"),
        ),
        migrations.AddField(
            model_name='trajet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='nombre_places',
            field=models.PositiveIntegerField(default=1, verbose_name='places disponibles'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='origine',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Lieu de départ'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='prix_par_place',
            field=models.PositiveIntegerField(default=2, verbose_name='Prix par place'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='duree',
            field=models.TimeField(verbose_name='durée du trajet'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='heure_depart',
            field=models.TimeField(verbose_name='Heure de départ'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/profile.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='id_conducteur',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='id_trajet',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='place_libre',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='point_arrive',
        ),
        migrations.RemoveField(
            model_name='trajet',
            name='point_depart',
        ),
    ]
