# Generated by Django 5.2.3 on 2025-06-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Trajet',
            new_name='tra',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('Utilisateur', 'tra')},
        ),
    ]
