# Generated by Django 5.2.3 on 2025-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0002_remove_trajet_description_alter_trajet_date_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajet',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Lieu d'arrivée"),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='origine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de départ'),
        ),
    ]
