# Generated by Django 5.2.3 on 2025-06-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0002_alter_utilisateur_num_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
