# Generated by Django 5.2.3 on 2025-06-16 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0002_alter_conducteur_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conducteur',
            name='mot_de_passe',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='num_tel',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='uniquement 10 chiffres.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='passager',
            name='mot_de_passe',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='passager',
            name='num_tel',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='uniquement 10 chiffres.', regex='^\\d{10}$')]),
        ),
    ]
