# Generated by Django 5.2.3 on 2025-06-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Convoiturage', '0003_alter_utilisateur_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/profile.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
